version: "3"
services:
  node:
    build:
      context: .
      dockerfile: operator.Dockerfile
    image: ghcr.io/layr-labs/incredible-squaring-avs/node:latest
  nodeplugin:
    build:
      context: .
      dockerfile: plugin.Dockerfile
    image: ghcr.io/layr-labs/incredible-squaring-avs/nodeplugin:latest
  aggregator:
    build:
      context: .
      dockerfile: aggregator.dockerfile
    image: ghcr.io/layr-labs/incredible-squaring/aggregator:latest